version: "3.3"

services:
  nginx:
    container_name: inception_nginx
    depends_on:
      - wordpress
    build:
      context: requirements/nginx/
    volumes:
      - html:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    container_name: inception_wordpress
    build:
      context: requirements/wordpress/
    volumes:
      - html:/var/www/html
    networks:
      - inception
    ports:
      - "9000:9000"
    depends_on:
      database:
         condition: service_healthy
    env_file:
      - .env
    restart: always

  database:
    container_name: inception_database
    build: requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/db

  html:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wp
